#!/bin/bash

# USAGE: zsconfuz-alt [--verbose] [-jN] ZSconfuz-file.txt
# This program has almost the same interface as zsconfuz
#   (it only lacks the capability to dynamically add commands to the command queue)
#   and simulates it using ninja
# (C) 2019 Erik Zscheile
# License: ISC

IS_VERBOSE=false
TMPFILE="$(mktemp)"

while [ $# -gt 1 ]; do
  case "$1" in
    (--verbose) IS_VERBOSE=true; NINJAOPTS+=" -v" ;;
    (*)         NINJAOPTS+=" $1" ;;
  esac
  shift
done

if ! [ -f "$1" ]; then
  echo "USAGE: zsconfuz-alt [--verbose] [-jN] [NINJAOPTS] ZSconfuz-file.txt"
  echo "NOTE: this program lacks the capability to dynamically add commands to the command queue"
  exit 1
fi

cleanup() {
  rm -rf "$TMPFILE" .zscfzFiles .ninja_*
}

trap cleanup EXIT
export PATH="$(dirname "$0")/../libexec/zsconfuz-alt:$PATH"
$IS_VERBOSE && echo zscfz2ninja.sh "$1"
zscfz2ninja.sh "$1" < "$1" > "$TMPFILE"
$IS_VERBOSE && echo ninja -f "$TMPFILE" $NINJAOPTS
NINJA_STATUS_SLEEP=inf ninja -f "$TMPFILE" $NINJAOPTS
