#!/bin/bash

if [[ -z $1 || -z $2 || -z $3 ]]; then
  echo "USAGE: chk_lib VARNAME FOUND_VN LIBNAME [ALTS...]"
  exit 1
fi

echo_n() {
  printf '%s' "$@"
}

. tent.sh || { echo "tent.sh not found"; exit 1; }

lib_found=false
var_name="$1"
found_vn="$2"
libsx=""
shift 2

LIBx2="LIBS_$1"

mkdir -p .temp
echo_n "int main(int argc, char **argv) { return 0; }" > ".temp/chklib_$$.c"

for lib in "${!LIBx2}" "$@"; do
  [ -z "$lib" ] && continue
  echo_n "checking for library $lib ... "
  libsx="$lib"
  echo "$lib" | grep -Fq - - || libsx="-l$lib"
  libsx="$(echo "$libsx" | sed -e 's/;/ /g')"
  if "$CC" $libsx -o ".temp/chklib_$$.x" ".temp/chklib_$$.c" &>/dev/null; then
    echo yes
    lib_found=true
    break
  fi
  echo no
done

rm -f ".temp/chklib_$$."*
printf "\000$found_vn=$lib_found\n"
$lib_found && printf "\000$var_name=$libsx\n"
